# Blog info
blog_name: World Observer
slogan: 路漫漫其修远兮，吾将上下而求索
url: https://blog.xiaofangwei.cn

# Set avatar (Absolute url and relative url)
avatar: /imgs/avatar.png

# Set favicon
favicon: /imgs/favicon.ico

# For seo
keywords: World Observer, world observer, xiaofangwei, blog, Xiao FangWei, Java, 后端开发

home_nav:
  - name: Blog
    url: /archives/
    target_blank: false #不在新页面打开
  # - name: Github
  #   url: https://github.com/no-sky
  #   target_blank: true #在新页面打开
  - name: Timeline
    url: /timeline/
    target_blank: false
  - name: Links
    url: /link/
    target_blank: false
  - name: Note
    url: https://note.xiaofangwei.cn
    target_blank: true
# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开
  # - name: RSS
  #   url: /atom.xml
  #   target_blank: true # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子
  url: /

search_slogan:
  isShow: true # true|fase
  text: 世界之大，搜索可达 ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 nosky@xiaofangwei.cn


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持创作
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /imgs/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /imgs/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: false
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.min.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics: UA-135962328-1
baidu_analytics: 

# Comment service


# 畅言, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  这里开启
  changyan_appid:
  changyan_appkey:

# gitalk评论组件，把下面的配置换成你的，官方文档: https://gitalk.github.io/
gitalk:
  enable: false # 如果使用 gitalk，请设置改之为true
  clientID: f911edd36913cac4f103
  clientSecret: f78cdecf141e6c6a12c1b3906bbd7c791d14b467
  repo: xfw.github.io
  owner: xiaofangwei
  admin: xiaofangwei


# gitment comment service
gitment:
  enable: false  # true | false  这里开启
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: true # 如果使用valine，请设置改之为true
  appid: eLCpjPGCcmy5wMIzcYnfSqc7-gzGzoHsz  # your leancloud application appid
  appkey: NFSLlbV1sG9bdOuLQpwqlRGz  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: retro # gravatar style
  guest_info: nick,mail # link # custom comment header
  pageSize: 10 # pagination size

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "博客：分享知识，分享乐趣"
    - "指导：己所不欲，勿施于人；耐心是第一生产力"
    - "特性：乐活与忧郁并存的矛盾体质"
    - "技能：擅后端开发，常用 Java"
    - "兴趣：阅读、健身、骑行"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@no-sky"
    text_value_url: https://github.com/no-sky
  - type: mail
    icon: icon-mail
    text_key: Mail
    text_value: "nosky@xiaofangwei.cn"
  #- type: location
  #  icon: icon-location
  #  text_value: 

link:
  - name: aqqje
    info: 相见亦无事，不遇长相思！
    url: http://aqqje.com/
    avatar: https://github.com/aqqje/Personal-repository/raw/master/aqqje/avater.jpg
  - name: 神仙散棒槌
    info: Royal Never Give up
    url: https://www.zhouguiqiang.com/
    avatar: https://s2.ax1x.com/2019/03/07/kxsEEq.jpg
  - name: Forsigner
    info: Find the bug of the world 
    url: http://forsigner.com/
    avatar: http://forsigner.com/images/avatar.jpg
  - name: 阁子
    info: 多可喜，亦多可悲 
    url: https://newdee.cf
    avatar: https://newdee.cf/images/favo.jpg
  - name: Troyyang
    info: Happy Coding, Happy Life!  
    url: https://troyyang.com
    avatar: https://troyyang.com/images/avatar-small.png
  - name: Ryan0up'S Blog (Halo作者)
    info: O ever youthful, O ever weeping.
    url: https://ryanc.cc/
    avatar: https://ryanc.cc/upload/2018/6/v2-ef180e77b63e636ad8e96f2f57897b71_hd2018062400420251.jpg
  - name: 纯洁的微笑
    info: 分享技术，品味人生
    url: http://www.ityouknow.com/
    avatar: https://avatars0.githubusercontent.com/u/4979648?s=460&v=4
  - name: FENews
    info: FENews 是一个前端技术分享的组织
    url: http://fenews.org/
    avatar: https://i.loli.net/2019/03/26/5c998b18eafcd.jpg
  - name: Randy Lu
    info: Blogging about life, tech and music.
    url: https://lutaonan.com
    avatar: https://ws3.sinaimg.cn/large/006tKfTcgy1fkuuijv4pwj30ku0na3zq.jpg
  - name: DIYgod
    info: 写代码是热爱，写到世界充满爱！
    url: https://diygod.me
    avatar: https://diygod.me/images/DIYgod.jpg
#project:
  # - type: personal
  #   name: fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
