name: Build and Update Github Pages

on: 
  push:
    branches:    
      - blog

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Use Node.js 10.x

        uses: actions/setup-node@v1

        with:

          node-version: "10.x"

      - name: Setup Hexo env

        env:

          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

          BRANCH: master

        run: |

          # set up private key for deploy

          mkdir -p ~/.ssh/

          echo "$ACCESS_TOKEN" | tr -d '\r' > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # set git infomation

          git config --global user.name 'xiaofangwei'

          git config --global user.email 'nosky.xfw@outlook.com'

          # install dependencies

          npm install -g hexo-cli

          npm install

          # install pandoc

          curl -s -L https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-linux.tar.gz | tar xvzf - -C $RUNNER_TOOL_CACHE/

      - name: Deploy

        run: |

          # add pandoc to PATH

          export PATH="$PATH:$RUNNER_TOOL_CACHE/pandoc-2.7.3/bin"

          # publish

          hexo clean
          
          hexo generate && hexo deploy